# Generated by Django 5.1.2 on 2024-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cruetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruetype_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_type',
        ),
    ]
