# Generated by Django 5.1.2 on 2024-10-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_crue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crue_name', models.CharField(max_length=30)),
                ('crue_photo', models.FileField(upload_to='Assets/Crue/')),
                ('cruetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_cruetype')),
            ],
        ),
    ]
