# Generated by Django 5.1.2 on 2024-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_crue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_crue',
        ),
    ]
