# Generated by Django 5.1.2 on 2024-10-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_tbl_crue'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('movie_release_date', models.DateField()),
                ('movie_description', models.CharField(max_length=100)),
                ('movie_poster', models.FileField(upload_to='Assets/Movie/')),
                ('movie_link', models.CharField(max_length=500)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_crue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crue_name', models.CharField(max_length=30)),
                ('crue_photo', models.FileField(upload_to='Assets/Crue/')),
                ('cruetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_cruetype')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_movie')),
            ],
        ),
    ]
